apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: batch
  name: batch
  namespace: default
spec:
  containers:
  - image: ubuntu
    name: batch
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
