FROM node:latest  #Add docker images should start with base image

RUN apt-get update

RUN apt-get install python

WORKDIR /app

ADD . /app

RUN npm install

#create react app prod build
RUN npm run build

EXPOSE 443

RUN npm run prodBuildServer

CMD ["npm", "run", "prod"]

#ENTRY POINT FLASK_APP=/OPT/src/app.py flask run


#each instruction above creates new layers on the images
#docker history command shows the size of each layer
#All the layers are cached -> so can restart fails builds from build step
#docker build . -t  dimu/hello_app

