# this does not create any contorl and it only introduce the API.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com # name must match the spec fields below, and be in the form: <plural>.<group>
spec:
  group: stable.example.com # group name to use for REST API: /apis/<group>/<version>
  scope: Namespaced # either Namespaced or Cluster
  names:
    plural: crontabs # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    singular: crontab # singular name to be used as an alias on the CLI and for display
    kind: CronTab # kind is normally the CamelCased singular type. Your resource manifests use this.
    shortNames: # shortNames allow shorter string to match your resource on the CLI
      - ct
  versions: # list of versions supported by this CustomResourceDefinition
    - name: v1
      served: true # Each version can be enabled/disabled by Served flag.
      storage: true # One and only one version must be marked as the storage version.
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer