apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
  - apiGroups: [""] # "" indicates the core API group. for core group leave it blank. for any other group -> mention the group name
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
    resouceNames: ["blue", "orange"] # optional resouceName -> this allows to block at resouce level. Like only blue and orange pods
  - apiGroups: [""]
    resources: ["ConfigMap"]
    verbs: ["create"]