apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 3  #pods come after one after the other when scale up. when remove the replicas -> apps get removed in reverse creation order
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
  serviceName: mysql-h
  podManagementPolicy: Parallel # change scaling policy to Parallel

