apiVersion: v1 # apps/v1
kind: Pod # pod, seervice , replica set, depolyment
metadata:
  name: mayapps-pod #name of the pod
  labels:
    app: myapp
    type: front-end
    costcenter: amer
spec:
  containers:
    - name: nginx-container
      image: nginx

#kubectl create -f pod-definition.yml