apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myClaim
spec:
  accessModes:
    #- ReadOnlyMany   #can mount many nodes
    #- ReadWriteOnce  can by mounted as a RW by a single node
    - ReadWriteMany  #many nodes can mount
  resources:
    requests:
      storage: 500i

