apiVersion: v1
kind: Service
metadata:
  name: mysql-h
spec:
  ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: testservice
  clusterIP: none   #this makes the service a headless service