#shared by all namespaces

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress-controller
    spec:
      containers:
        - name: nginx-ingress-controllers
          image: nginx/nginx-ingress  # special build of nginx to be used as kub Ingress controller
      args:
        - /nginx-ingress-controller # must pass this to start the nginx service
        - 00configmap=$(POD_NAMESPSCE)/nginx-configurations #this must be passed to disable default configs of nginx
      env: #must pass below two
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
             fieldRef:
               fieldPath: metadata.name
      ports:
        - name: https
          containerPort: 443
        - name: http
          containerPort: 80
