apiVersion: v1
kind: ReplicationController
metadata:
  name: mayapps-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: mayapps-pod
      labels:
        app: myapp
        type: front-end
        costcenter: amer
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3


